### ISSUE TITLE
Move examples to another repo

### ISSUE THREAD

**Issue by shijianjian** [torchpipe/torchpipe#19]
Current main repo is around 100 MB when download those examples and the history files. It is better to move those unnecessary files to another repo to keep this one cleaner, and easy to clone.

**Comment by tp-nan** [comment]
Yes, some examples need to be moved elsewhere, such as ppocr and YOLOX, as their models cannot be generated online. Meanwhile, the corresponding links in the [online documentation](https://torchpipe.github.io/docs/showcase) also need to be updated.

**Comment by shijianjian** [comment]
Maybe put all the models on Huggingface. No need to update those many links.
