### ISSUE TITLE
关于ScheduleV3 banckend的一些问题

### ISSUE THREAD

**Issue by BaofengZan** [torchpipe/torchpipe#33]
对于 Schedule这里我不是很明白其作用。 主要是多个模型或者多个实例的调度吗？   在toml文件中是怎样配置的呢？没有看到相应的demo

**Comment by tp-nan** [comment]
Schedule 负责多实例和batching功能， 对于TensorRT推理，toml文件中的 instance_num max batching_timeout 三个参数和它有关（max batch size是Schedule调用Backend的max()接口获得的）。TensorrtTensor后端通过 instance_num max两个参数确定了optim profiles 和max batch size。

demo: 
```batching
import torch, torchpipe
model = torchpipe.pipe({'model': model_path,
                        'backend': "Sequential[cvtColorTensor,TensorrtTensor,SyncTensor]", # Backend engine, see backend API reference documentation
                        'instance_num': 2, 'batching_timeout': '5', # Number of instances and timeout time
                        'max': 4, # Maximum value of the model optimization range, which can also be '4x3x224x224'
                        'mean': '123.675, 116.28, 103.53', # 255*"0.485, 0.456, 0.406"
                        'std': '58.395, 57.120, 57.375', # Fusion into TensorRT network
                        'color': 'rgb'}) # Parameters for cvtColorTensor backend: target color space order
data = torch.zeros((1, 3, 224, 224)) # or torch.from_numpy(...)
input = {"data": data, 'color': 'bgr'}
model(input)  # Can be called in parallel with multiple threads
# Use "result" as the data output identifier; of course, other key values ​​can also be custom written
print(input["result"].shape)  # If failed, this key value must not exist, even if it already exists when input.
```

**Comment by BaofengZan** [comment]
感谢，  我再描述下我的疑问：     比如我有个 toml  :    [jpg_decoder]  --> 然后后面接两个平级的检测器 [yolov8] 和 [yolov7]    ，其中每个检测器instance_num都是4。 这里的Schedule只是在每个检测器内部 调度4个实例吗？还是 在两个检测器之间也会调度（比如优先执行yolov7 这样的，还是说就是os/GPU自己去调度当前运行哪个检测器？）

**Comment by tp-nan** [comment]
>  这里的Schedule只是在每个检测器内部 调度4个实例吗？

ScheduleV3只是在每个检测器内部 调度4个实例. 有4个yolov8实例和4个yolov7实例。4个yolov8构成一个节点。

>  还是 在两个检测器之间也会调度（比如优先执行yolov7 这样的，还是说就是os/GPU自己去调度当前运行哪个检测器？ 

[jpg_decoder] [yolov8] 和 [yolov7] 三个节点之间的调度内部由PipelineV3完成，单个request保持顺序执行，但多个request会有流水线并行进行overlap。提交的GPU任务由GPU驱动自行进行抢占式执行（多个实例有独立的多个cuda流进行并发）

**Comment by BaofengZan** [comment]
好的，感谢回答， 我大概理解了 。我继续debug 理解理解。
