### ISSUE TITLE
torchpipe与torchgpipe有什么区别么？

### ISSUE THREAD

**Issue by dreaming12580** [torchpipe/torchpipe#8]
torchpipe与torchgpipe有什么区别么？ 两个库名字很相似

**Comment by tp-nan** [comment]
torchgpipe主要是用于训练时的流水线并行；torchpipe用于推理服务的吞吐最优化，支持tensorrt等第三方加速后端，并且主要关注最简化的ensemble语法

torchgpipe is mainly used for pipeline parallelism during training; torchpipe is used for optimizing throughput of inference services, supporting third-party acceleration backends such as TensorRT, and mainly focuses on simplified ensemble syntax.

**Comment by dreaming12580** [comment]
got it
