### ISSUE TITLE
有多节点多进程的实现么？

### ISSUE THREAD

**Issue by dreaming12580** [torchpipe/torchpipe#9]
只发现了单节点单进程多线程的examples,  有多节点多进程的torchpipe实现么？ 单节点的话， triton的 ensemble 是可以做到多进程单线程pipeline，对于python, 更能充分利用cpu, 只是没有torchpipe多线程轻量,  那比triton的 ensemble的性能好的原因是什么？ 都是cpu 与 gpu拆分成流水线

**Comment by tp-nan** [comment]
感谢你对本项目的关注。

比triton ensemble性能有优势的地方
1. 调度和后端都在c++中，多线程也能充分利用cpu
2. 多进程通常产生多个cuda context，有[overhead](https://torchpipe.github.io/zh/docs/preliminaries/cuda_stream#%E8%99%9A%E6%8B%9F%E5%8C%96) ：
3. ensemble 对应我们的 [Sequential](https://torchpipe.github.io/zh/docs/Intra-node/Sequential)，无法处理子节点max batch size，或者instance num需要变化的情况
4. 与torch的绑定使得更方便的集成[更细粒度的gpu后端](https://torchpipe.github.io/zh/docs/backend-reference/torch)以及回退到python的可能

多进程方面，有过这方面的想法，比如在后端层面提供一个“RPC”或者“多进程配器” 后端: https://github.com/torchpipe/torchpipe/blob/bae8bee29fdabb81d2584322c3955fb4ec8f1a65/torchpipe/csrc/core/src/Remote.cpp#L28

这部分主要现在我这边没有应用场景，还没搞清楚怎么设计比较好；另外python的子解释器也在我们的考虑范围。

**Comment by dreaming12580** [comment]
多进程通常产生多个cuda context，有[overhead](https://torchpipe.github.io/zh/docs/preliminaries/cuda_stream#cuda%E4%B8%8A%E4%B8%8B%E6%96%87cuda-context) ：  这里ensemble triton 的多进程是指比如有6个进程,   
 2个进程是cpu任务， 处理preprocess数据， 1 个进程是gpu任务， 处理extract feature任务， 2个进程是postprocess数据， 1个进程是detection任务， 这样的话，是进程之间进行pipeline， 没有产生多个cuda context，没有overhead吧？

**Comment by tp-nan** [comment]
> 多进程通常产生多个cuda context，有[overhead](https://torchpipe.github.io/zh/docs/preliminaries/cuda_stream#cuda%E4%B8%8A%E4%B8%8B%E6%96%87cuda-context) ： 这里ensemble triton 的多进程是指比如有6个进程, 2个进程是cpu任务， 处理preprocess数据， 1 个进程是gpu任务， 处理extract feature任务， 2个进程是postprocess数据， 1个进程是detection任务， 这样的话，是进程之间进行pipeline， 没有产生多个cuda context，没有overhead吧？

是的，这样没有gpu的overhead

**Comment by dreaming12580** [comment]
> > 多进程通常产生多个cuda context，有[overhead](https://torchpipe.github.io/zh/docs/preliminaries/cuda_stream#cuda%E4%B8%8A%E4%B8%8B%E6%96%87cuda-context) ： 这里ensemble triton 的多进程是指比如有6个进程, 2个进程是cpu任务， 处理preprocess数据， 1 个进程是gpu任务， 处理extract feature任务， 2个进程是postprocess数据， 1个进程是detection任务， 这样的话，是进程之间进行pipeline， 没有产生多个cuda context，没有overhead吧？
> 
> 是的，如果detection也是cpu任务的话，只有一个gpu进程，是没有gpu的overhead的。理论上triton通过极限的优化，也能达到最优性能。我们的目标群体是算法工程师，对他们来说，这种最优比较难达到

用多个进程跑一个gpu任务感觉没多大意义吧， 同时间的请求多了，组成batch是不是更好

**Comment by tp-nan** [comment]
> > > 多进程通常产生多个cuda context，有[overhead](https://torchpipe.github.io/zh/docs/preliminaries/cuda_stream#cuda%E4%B8%8A%E4%B8%8B%E6%96%87cuda-context) ： 这里ensemble triton 的多进程是指比如有6个进程, 2个进程是cpu任务， 处理preprocess数据， 1 个进程是gpu任务， 处理extract feature任务， 2个进程是postprocess数据， 1个进程是detection任务， 这样的话，是进程之间进行pipeline， 没有产生多个cuda context，没有overhead吧？
> > 
> > 
> > 是的，如果detection也是cpu任务的话，只有一个gpu进程，是没有gpu的overhead的。理论上triton通过极限的优化，也能达到最优性能。我们的目标群体是算法工程师，对他们来说，这种最优比较难达到
> 
> 用多个进程跑一个gpu任务感觉没多大意义吧， 同时间的请求多了，组成batch是不是更好

我不太清楚triton的实现，进程还是线程应该不影响组batch：多进程下，可以每个进程一个实例，10路并发输入，系统两个实例，每个实例最大batchsize=4， 这样也是可以的（2*4 约等于10），不影响组batch；batchsize过大也不好
